// Code generated by "stringer -type=Token"; DO NOT EDIT.

package tokens

import "strconv"

const _Token_name = "EndOfFileEndOfLineCommaAssignmentLocalReferenceAllLocalReferencesSubtractionAdditionDivisionMultiplicationNotEqualityCheckLessThanCheckLessThanOrEqualCheckGreaterThanCheckGreaterThanOrEqualCheckStartOfExpressionEndOfExpressionStartOfStructEndOfStructStartOfArrayEndOfArrayStartOfSwitchEndOfSwitchSwitchCaseDefaultSwitchCaseStartOfFunctionEndOfFunctionReturnBreakStartOfIfElseElseIfEndOfIfOptimisedIfOptimisedElseIntegerFloatNameShortJumpChecksumTableEntryNamespaceAccessInvalid"

var _Token_index = [...]uint16{0, 9, 18, 23, 33, 47, 65, 76, 84, 92, 106, 109, 122, 135, 155, 171, 194, 211, 226, 239, 250, 262, 272, 285, 296, 306, 323, 338, 351, 357, 362, 371, 375, 381, 388, 399, 412, 419, 424, 428, 437, 455, 470, 477}

func (i Token) String() string {
	if i < 0 || i >= Token(len(_Token_index)-1) {
		return "Token(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Token_name[_Token_index[i]:_Token_index[i+1]]
}
