// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package tokens

import "strconv"

const _TokenType_name = "EndOfFileEndOfLineCommaDotAssignmentLocalReferenceAllLocalReferencesStringLocalStringPairVectorWhileRepeatBreakSubtractionAdditionDivisionMultiplicationNotOrAndEqualityCheckLessThanCheckLessThanOrEqualCheckGreaterThanCheckGreaterThanOrEqualCheckExecuteRandomBlockRandomRangeStartOfExpressionEndOfExpressionStartOfStructEndOfStructStartOfArrayEndOfArrayStartOfSwitchEndOfSwitchSwitchCaseDefaultSwitchCaseStartOfFunctionEndOfFunctionReturnStartOfIfElseElseIfEndOfIfOptimisedIfOptimisedElseIntegerFloatNameShortJumpLongJumpNameTableEntryNamespaceAccessInvalid"

var _TokenType_index = [...]uint16{0, 9, 18, 23, 26, 36, 50, 68, 74, 85, 89, 95, 100, 106, 111, 122, 130, 138, 152, 155, 157, 160, 173, 186, 206, 222, 245, 263, 274, 291, 306, 319, 330, 342, 352, 365, 376, 386, 403, 418, 431, 437, 446, 450, 456, 463, 474, 487, 494, 499, 503, 512, 520, 534, 549, 556}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
